//THIS FILE IS AUTOGENERATED BY GHOSTCOMPILER. DON'T MODIFY OR ALTER.
using System;
using AOT;
using Unity.Burst;
using Unity.Networking.Transport;
using Unity.NetCode.LowLevel.Unsafe;
using Unity.Collections.LowLevel.Unsafe;
using Unity.Entities;
using Unity.Collections;
using Unity.NetCode;
using Unity.Transforms;
using Unity.Mathematics;

namespace Assembly_CSharp.Generated
{
    [BurstCompile]
    public struct PlayerTagComponentGhostComponentSerializer
    {
        static GhostComponentSerializer.State GetState()
        {
            // This needs to be lazy initialized because otherwise there is a depenency on the static initialization order which breaks il2cpp builds due to TYpeManager not being initialized yet
            if (!s_StateInitialized)
            {
                s_State = new GhostComponentSerializer.State
                {
                    GhostFieldsHash = 4379934046830037180,
                    ExcludeFromComponentCollectionHash = 0,
                    ComponentType = ComponentType.ReadWrite<PlayerTagComponent>(),
                    ComponentSize = UnsafeUtility.SizeOf<PlayerTagComponent>(),
                    SnapshotSize = UnsafeUtility.SizeOf<Snapshot>(),
                    ChangeMaskBits = ChangeMaskBits,
                    SendMask = GhostComponentSerializer.SendMask.Interpolated | GhostComponentSerializer.SendMask.Predicted,
                    SendToOwner = SendToOwnerType.All,
                    SendForChildEntities = 1,
                    VariantHash = 0,
                    CopyToSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyToSnapshot),
                    CopyFromSnapshot =
                        new PortableFunctionPointer<GhostComponentSerializer.CopyToFromSnapshotDelegate>(CopyFromSnapshot),
                    RestoreFromBackup =
                        new PortableFunctionPointer<GhostComponentSerializer.RestoreFromBackupDelegate>(RestoreFromBackup),
                    PredictDelta = new PortableFunctionPointer<GhostComponentSerializer.PredictDeltaDelegate>(PredictDelta),
                    CalculateChangeMask =
                        new PortableFunctionPointer<GhostComponentSerializer.CalculateChangeMaskDelegate>(
                            CalculateChangeMask),
                    Serialize = new PortableFunctionPointer<GhostComponentSerializer.SerializeDelegate>(Serialize),
                    Deserialize = new PortableFunctionPointer<GhostComponentSerializer.DeserializeDelegate>(Deserialize),
                    #if UNITY_EDITOR || DEVELOPMENT_BUILD
                    ReportPredictionErrors = new PortableFunctionPointer<GhostComponentSerializer.ReportPredictionErrorsDelegate>(ReportPredictionErrors),
                    #endif
                };
                #if UNITY_EDITOR || DEVELOPMENT_BUILD
                s_State.NumPredictionErrorNames = GetPredictionErrorNames(ref s_State.PredictionErrorNames);
                #endif
                s_StateInitialized = true;
            }
            return s_State;
        }
        private static bool s_StateInitialized;
        private static GhostComponentSerializer.State s_State;
        public static GhostComponentSerializer.State State => GetState();
        public struct Snapshot
        {
            public int coordinat_x;
            public int coordinat_y;
            public int chunkCoordinat_x;
            public int chunkCoordinat_y;
        }
        public const int ChangeMaskBits = 4;
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyToSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData, snapshotOffset + snapshotStride*i);
                ref var component = ref GhostComponentSerializer.TypeCast<PlayerTagComponent>(componentData, componentStride*i);
                ref var serializerState = ref GhostComponentSerializer.TypeCast<GhostSerializerState>(stateData, 0);
                snapshot.coordinat_x = (int) component.coordinat.x;
                snapshot.coordinat_y = (int) component.coordinat.y;
                snapshot.chunkCoordinat_x = (int) component.chunkCoordinat.x;
                snapshot.chunkCoordinat_y = (int) component.chunkCoordinat.y;
            }
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CopyToFromSnapshotDelegate))]
        private static void CopyFromSnapshot(IntPtr stateData, IntPtr snapshotData, int snapshotOffset, int snapshotStride, IntPtr componentData, int componentStride, int count)
        {
            for (int i = 0; i < count; ++i)
            {
                var deserializerState = GhostComponentSerializer.TypeCast<GhostDeserializerState>(stateData, 0);
                ref var snapshotInterpolationData = ref GhostComponentSerializer.TypeCast<SnapshotData.DataAtTick>(snapshotData, snapshotStride*i);
                ref var snapshotBefore = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotBefore, snapshotOffset);
                ref var snapshotAfter = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotInterpolationData.SnapshotAfter, snapshotOffset);
                //Compute the required owner mask for the components and buffers by retrievieng the ghost owner id from the data for the current tick.
                if (snapshotInterpolationData.GhostOwner > 0)
                {
                    var requiredOwnerMask = snapshotInterpolationData.GhostOwner == deserializerState.GhostOwner
                        ? SendToOwnerType.SendToOwner
                        : SendToOwnerType.SendToNonOwner;
                    if ((deserializerState.SendToOwner & requiredOwnerMask) == 0)
                        continue;
                }
                deserializerState.SnapshotTick = snapshotInterpolationData.Tick;
                float snapshotInterpolationFactorRaw = snapshotInterpolationData.InterpolationFactor;
                float snapshotInterpolationFactor = snapshotInterpolationFactorRaw;
                ref var component = ref GhostComponentSerializer.TypeCast<PlayerTagComponent>(componentData, componentStride*i);
                component.coordinat.x = (int) snapshotBefore.coordinat_x;
                component.coordinat.y = (int) snapshotBefore.coordinat_y;
                component.chunkCoordinat.x = (int) snapshotBefore.chunkCoordinat_x;
                component.chunkCoordinat.y = (int) snapshotBefore.chunkCoordinat_y;

            }
        }


        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.RestoreFromBackupDelegate))]
        private static void RestoreFromBackup(IntPtr componentData, IntPtr backupData)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<PlayerTagComponent>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<PlayerTagComponent>(backupData, 0);
            component.coordinat.x = backup.coordinat.x;
            component.coordinat.y = backup.coordinat.y;
            component.chunkCoordinat.x = backup.chunkCoordinat.x;
            component.chunkCoordinat.y = backup.chunkCoordinat.y;
        }

        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.PredictDeltaDelegate))]
        private static void PredictDelta(IntPtr snapshotData, IntPtr baseline1Data, IntPtr baseline2Data, ref GhostDeltaPredictor predictor)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline1 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline1Data);
            ref var baseline2 = ref GhostComponentSerializer.TypeCast<Snapshot>(baseline2Data);
            snapshot.coordinat_x = predictor.PredictInt(snapshot.coordinat_x, baseline1.coordinat_x, baseline2.coordinat_x);
            snapshot.coordinat_y = predictor.PredictInt(snapshot.coordinat_y, baseline1.coordinat_y, baseline2.coordinat_y);
            snapshot.chunkCoordinat_x = predictor.PredictInt(snapshot.chunkCoordinat_x, baseline1.chunkCoordinat_x, baseline2.chunkCoordinat_x);
            snapshot.chunkCoordinat_y = predictor.PredictInt(snapshot.chunkCoordinat_y, baseline1.chunkCoordinat_y, baseline2.chunkCoordinat_y);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.CalculateChangeMaskDelegate))]
        private static void CalculateChangeMask(IntPtr snapshotData, IntPtr baselineData, IntPtr bits, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask;
            changeMask = (snapshot.coordinat_x != baseline.coordinat_x) ? 1u : 0;
            changeMask |= (snapshot.coordinat_y != baseline.coordinat_y) ? (1u<<1) : 0;
            changeMask |= (snapshot.chunkCoordinat_x != baseline.chunkCoordinat_x) ? (1u<<2) : 0;
            changeMask |= (snapshot.chunkCoordinat_y != baseline.chunkCoordinat_y) ? (1u<<3) : 0;
            GhostComponentSerializer.CopyToChangeMask(bits, changeMask, startOffset, 4);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.SerializeDelegate))]
        private static void Serialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamWriter writer, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                writer.WritePackedIntDelta(snapshot.coordinat_x, baseline.coordinat_x, compressionModel);
            if ((changeMask & (1 << 1)) != 0)
                writer.WritePackedIntDelta(snapshot.coordinat_y, baseline.coordinat_y, compressionModel);
            if ((changeMask & (1 << 2)) != 0)
                writer.WritePackedIntDelta(snapshot.chunkCoordinat_x, baseline.chunkCoordinat_x, compressionModel);
            if ((changeMask & (1 << 3)) != 0)
                writer.WritePackedIntDelta(snapshot.chunkCoordinat_y, baseline.chunkCoordinat_y, compressionModel);
        }
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.DeserializeDelegate))]
        private static void Deserialize(IntPtr snapshotData, IntPtr baselineData, ref DataStreamReader reader, ref NetworkCompressionModel compressionModel, IntPtr changeMaskData, int startOffset)
        {
            ref var snapshot = ref GhostComponentSerializer.TypeCast<Snapshot>(snapshotData);
            ref var baseline = ref GhostComponentSerializer.TypeCast<Snapshot>(baselineData);
            uint changeMask = GhostComponentSerializer.CopyFromChangeMask(changeMaskData, startOffset, ChangeMaskBits);
            if ((changeMask & (1 << 0)) != 0)
                snapshot.coordinat_x = reader.ReadPackedIntDelta(baseline.coordinat_x, compressionModel);
            else
                snapshot.coordinat_x = baseline.coordinat_x;
            if ((changeMask & (1 << 1)) != 0)
                snapshot.coordinat_y = reader.ReadPackedIntDelta(baseline.coordinat_y, compressionModel);
            else
                snapshot.coordinat_y = baseline.coordinat_y;
            if ((changeMask & (1 << 2)) != 0)
                snapshot.chunkCoordinat_x = reader.ReadPackedIntDelta(baseline.chunkCoordinat_x, compressionModel);
            else
                snapshot.chunkCoordinat_x = baseline.chunkCoordinat_x;
            if ((changeMask & (1 << 3)) != 0)
                snapshot.chunkCoordinat_y = reader.ReadPackedIntDelta(baseline.chunkCoordinat_y, compressionModel);
            else
                snapshot.chunkCoordinat_y = baseline.chunkCoordinat_y;
        }
        #if UNITY_EDITOR || DEVELOPMENT_BUILD
        [BurstCompile]
        [MonoPInvokeCallback(typeof(GhostComponentSerializer.ReportPredictionErrorsDelegate))]
        private static void ReportPredictionErrors(IntPtr componentData, IntPtr backupData, ref UnsafeList<float> errors)
        {
            ref var component = ref GhostComponentSerializer.TypeCast<PlayerTagComponent>(componentData, 0);
            ref var backup = ref GhostComponentSerializer.TypeCast<PlayerTagComponent>(backupData, 0);
            int errorIndex = 0;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.coordinat.x - backup.coordinat.x));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.coordinat.y - backup.coordinat.y));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.chunkCoordinat.x - backup.chunkCoordinat.x));
            ++errorIndex;
            errors[errorIndex] = math.max(errors[errorIndex], math.abs(component.chunkCoordinat.y - backup.chunkCoordinat.y));
            ++errorIndex;
        }
        private static int GetPredictionErrorNames(ref FixedString512 names)
        {
            int nameCount = 0;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("coordinat.x"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("coordinat.y"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("chunkCoordinat.x"));
            ++nameCount;
            if (nameCount != 0)
                names.Append(new FixedString32(","));
            names.Append(new FixedString64("chunkCoordinat.y"));
            ++nameCount;
            return nameCount;
        }
        #endif
    }
}
